name: Docker Image workflow
on:
   push:
     branches:
         - main
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
       
       - name: Print a message
         run: echo "Hello, Doremon"
            
